version: "3"

services:
  # The express api.
  api:
    container_name: blog_api
    command: npm run dev
    build: .
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  # MongoDB database.
  mongodb:
    container_name: blog_api_mongodb
    image: mongo:4.2.2
    ports:
      - 27017:27017